name: mada-adm

services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
    volumes:
      - ./bin:/app/bin
      - ./commands/.args:/app/commands/.args
      - ./db/.sqlite:/app/db/.sqlite
      - ./db/.ca-certificates:/app/db/.ca-certificates
      - ./redis/.ca-certificates:/app/redis/.ca-certificates
    depends_on:
      - redis
    networks:
      - mada-adm-network

  redis:
    image: redis:alpine3.23
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - mada-adm-network

volumes:
  redis-data:

networks:
  mada-adm-network:
